### ISSUE TITLE
Example not working with documented commands and configuration

### ISSUE THREAD

**Issue by BeardInASuit** [exposr/exposrd#67]
The docker command  `docker run --rm -ti ghcr.io/exposr/exposr:latest -s http://host.docker.internal:8080/ tunnel connect example http://example.com` doesn't work since it seems that `exposrd` doens't create the tunnel before configuring it.

When using each command independently, it works:

```
docker run --rm -ti ghcr.io/exposr/exposr:latest -s http://host.docker.internal:8080/ account create
docker run --rm -ti ghcr.io/exposr/exposr:latest -s http://host.docker.internal:8080/ -a 2648-5PRJ-TWMN-XPXJ tunnel create
docker run --rm -ti ghcr.io/exposr/exposr:latest -s https://tunnel.dev.byrnu.com -a 2648-5PRJ-TWMN-XPXJ tunnel connect blue-fox-6 http://example.com
```

**Comment by fredriklindberg** [comment]
There was a regression in the command parser of the client. It's fixed in client version 0.10.

Pull ghcr.io/exposr/exposr:latest to update (or use ghcr.io/exposr/exposr:v0.10.0)
